export const projects = [
  {
    id: 1,
    title: "Earthquake Predictor",
    description: "A website that locates and predicts earthquakes",
    image: "/images/earthquakepredictor.png",
    tags: ["React.js", "APIs", "Tailwind CSS"],
    demo: "https://earthquake-predictor-wheat.vercel.app/",
    demoStatus: "deployed",
    github: "https://github.com/DavidAsrorxonov/Earthquake-Predictor",
    githubAccess: "public",
  },
  {
    id: 2,
    title: "Job Site Tracker",
    description:
      "A full-stack web application for tracking and managing job applications without any external tools.",
    image: "/images/jst.png",
    tags: ["React.js", "Node.js", "PostgreSQL", "APIs", "Tailwind CSS"],
    demo: "#",
    demoStatus: "not deployed",
    github: "https://github.com/DavidAsrorxonov/JST-2.0",
    githubAccess: "public",
  },
  {
    id: 3,
    title: "Velvet Mojito",
    description: "An interactive website made with GSAP",
    image: "/images/mojito.png",
    tags: ["React.js", "GSAP", "HTML/CSS", "Tailwind CSS"],
    demo: "https://mojito-webpage.vercel.app/",
    demoStatus: "deployed",
    github: "https://github.com/DavidAsrorxonov/mojito_webpage",
    githubAccess: "public",
  },
  {
    id: 4,
    title: "Aura 2.0",
    description:
      "A website for education centers that helps manage their student and tutor data",
    image: "/images/aura.png",
    tags: [
      "React.js",
      "Node.js",
      "PostgreSQL",
      "Tailwind CSS",
      "APIs",
      "Socket.io",
    ],
    demo: "https://langapex.uz",
    demoStatus: "deployed",
    github: "",
    githubAccess: "private",
  },
];
