export const projects = [
  {
    id: 1,
    title: "Earthquake Predictor",
    description: "A website that locates and predicts earthquakes",
    image: "/images/earthquakepredictor.png",
    tags: ["React.js", "APIs", "Tailwind CSS"],
    demo: "https://earthquake-predictor-wheat.vercel.app/",
    demoStatus: "deployed",
    github: "https://github.com/DavidAsrorxonov/Earthquake-Predictor",
    githubAccess: "public",
  },
  {
    id: 2,
    title: "Job Site Tracker",
    description:
      "A full-stack web application for tracking and managing job applications without any external tools.",
    image: "/images/jst2.png",
    tags: ["React.js", "Node.js", "PostgreSQL", "APIs", "Tailwind CSS"],
    demo: "#",
    demoStatus: "not deployed",
    github: "https://github.com/DavidAsrorxonov/JST-2.0",
    githubAccess: "public",
  },
  {
    id: 3,
    title: "LMS Course Platform",
    description:
      "An online learning platform where users can find online tutorials and watch them and admins can upload videos",
    image: "/images/lmsplatform.png",
    tags: [
      "React.js",
      "HTML/CSS",
      "Tailwind CSS",
      "Next.js",
      "APIs",
      "Zod",
      "Prisma",
      "MongoDB",
      "TypeScript",
    ],
    demo: "https://lms-course-platform-olive.vercel.app/",
    demoStatus: "deployed",
    github: "https://github.com/DavidAsrorxonov/lms_course_platform",
    githubAccess: "public",
  },
  {
    id: 4,
    title: "Care Pulse",
    description:
      "A hospital management platform for hospitals to manage their patient data and for patients to arrange meetings with doctors",
    image: "/images/carepulse.png",
    tags: [
      "Next.js",
      "React.js",
      "Node.js",
      "MongoDB",
      "Tailwind CSS",
      "APIs",
      "Socket.io",
    ],
    demo: "https://care-pulse-two-tau.vercel.app/",
    demoStatus: "deployed",
    github: "https://github.com/DavidAsrorxonov/Care-Pulse",
    githubAccess: "public",
  },
];
